/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filefairy;

import filefairy.Containers.Formats;
import filefairy.Containers.Functions;
import filefairy.Containers.Help;
import filefairy.Containers.Rename;
import filefairy.Containers.Variables;
import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.Toolkit;
import javax.swing.SwingUtilities;
import static sun.security.ssl.Debug.Help;

/**
 *
 * @author gabri
 */
public class Frame extends javax.swing.JFrame
{

    // Co-ordinates of mouse pointer - used for titlebar drag functionality
    int xMouse, yMouse;
    //Adding layout
    GridBagLayout layout = new GridBagLayout();
    Rename rename;
    Functions functions;
    Formats formats;
    Variables variables;
    Help help;

    public Frame()
    {
        initComponents();
        setLocationRelativeTo(null);
        dynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        // Set default panel to be selected
        lblRename.setBackground(new Color(0, 0, 0));
        rename = new Rename();
        dynamicPanel.add(rename, c);
        rename.setVisible(true);
        // Add all panels but setVisible = false    
        functions = new Functions();
        formats = new Formats();
        variables = new Variables();
        help = new Help();
        dynamicPanel.add(functions, c);
        dynamicPanel.add(formats, c);
        dynamicPanel.add(variables, c);
        dynamicPanel.add(help, c);
        functions.setVisible(false);
        formats.setVisible(false);
        variables.setVisible(false);
        help.setVisible(false);
        //Setting names for sidemenu items
        lblHamburgerMenu.setName("menu");
        lblRename.setName("rename");
        lblFunction.setName("function");
        lblFormats.setName("formats");
        lblVariables.setName("variables");
        lblHelp.setName("help");
        
        //CREATE VARIABLES FOR STATE OF SIDEMENU BUTTON - I.E. CLICKED OR NOT
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dynamicPanel = new javax.swing.JPanel();
        sideMenu = new javax.swing.JPanel();
        lblHelp = new javax.swing.JLabel();
        lblFormats = new javax.swing.JLabel();
        lblRename = new javax.swing.JLabel();
        lblFunction = new javax.swing.JLabel();
        lblVariables = new javax.swing.JLabel();
        lblHamburgerMenu = new javax.swing.JLabel();
        titleBar = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        FrameDrag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(Frame.class.getResource("Resources/img/logoIcon.png")));
        setIconImages(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dynamicPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 1190, 750));

        sideMenu.setBackground(new java.awt.Color(39, 43, 54));
        sideMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHelp.setBackground(new java.awt.Color(39, 43, 54));
        lblHelp.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblHelp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/HelpIcon.png"))); // NOI18N
        lblHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHelp.setOpaque(true);
        lblHelp.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblHelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblHelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblHelpMouseExited(evt);
            }
        });
        sideMenu.add(lblHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 502, 100, 70));

        lblFormats.setBackground(new java.awt.Color(39, 43, 54));
        lblFormats.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblFormats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFormats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/FormatIcon.png"))); // NOI18N
        lblFormats.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFormats.setOpaque(true);
        lblFormats.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFormatsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblFormatsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblFormatsMouseExited(evt);
            }
        });
        sideMenu.add(lblFormats, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 362, 100, 70));

        lblRename.setBackground(new java.awt.Color(39, 43, 54));
        lblRename.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblRename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRename.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/RenameIcon.png"))); // NOI18N
        lblRename.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRename.setOpaque(true);
        lblRename.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblRenameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblRenameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblRenameMouseExited(evt);
            }
        });
        sideMenu.add(lblRename, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 220, 100, 70));

        lblFunction.setBackground(new java.awt.Color(39, 43, 54));
        lblFunction.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblFunction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFunction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/SuperScriptIcon.png"))); // NOI18N
        lblFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFunction.setOpaque(true);
        lblFunction.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblFunctionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblFunctionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblFunctionMouseExited(evt);
            }
        });
        sideMenu.add(lblFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 291, 100, 70));

        lblVariables.setBackground(new java.awt.Color(39, 43, 54));
        lblVariables.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblVariables.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVariables.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/VariableIcon.png"))); // NOI18N
        lblVariables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVariables.setOpaque(true);
        lblVariables.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblVariablesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblVariablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblVariablesMouseExited(evt);
            }
        });
        sideMenu.add(lblVariables, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 433, 100, 70));

        lblHamburgerMenu.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblHamburgerMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHamburgerMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/MenuIcon.png"))); // NOI18N
        lblHamburgerMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideMenu.add(lblHamburgerMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 92, 60, -1));

        getContentPane().add(sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 820));

        titleBar.setBackground(new java.awt.Color(204, 204, 204));
        titleBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimize.setBackground(new java.awt.Color(204, 204, 204));
        lblMinimize.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/minimizeIcon.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblMinimizeMouseExited(evt);
            }
        });
        titleBar.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 70, 70));

        lblExit.setBackground(new java.awt.Color(204, 204, 204));
        lblExit.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filefairy/Resources/img/ExitIcon.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblExitMouseExited(evt);
            }
        });
        titleBar.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 70, 70));

        FrameDrag.setBackground(new java.awt.Color(192, 192, 192));
        FrameDrag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FrameDrag.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                FrameDragMouseDragged(evt);
            }
        });
        FrameDrag.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                FrameDragMousePressed(evt);
            }
        });
        titleBar.add(FrameDrag, new org.netbeans.lib.awtextra.AbsoluteConstraints(-104, -4, 1290, 70));

        getContentPane().add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1190, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblExitMouseClicked
    {//GEN-HEADEREND:event_lblExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void FrameDragMouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FrameDragMouseDragged
    {//GEN-HEADEREND:event_FrameDragMouseDragged
        // Adds drag functionality to custom titlebar        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_FrameDragMouseDragged

    private void FrameDragMousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_FrameDragMousePressed
    {//GEN-HEADEREND:event_FrameDragMousePressed
        // Gets co-ordinates of mouse pointer when initializing the drag in the titlebar        
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_FrameDragMousePressed

    private void lblFunctionMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFunctionMouseEntered
    {//GEN-HEADEREND:event_lblFunctionMouseEntered
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblFunction, true);
    }//GEN-LAST:event_lblFunctionMouseEntered

    private void lblFunctionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFunctionMouseClicked
    {//GEN-HEADEREND:event_lblFunctionMouseClicked
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblFunction, true);
        lblFunction.setBackground(new Color(0, 0, 0));
        rename.setVisible(false);
        functions.setVisible(true);
        variables.setVisible(false);
        help.setVisible(false);
        formats.setVisible(false);
    }//GEN-LAST:event_lblFunctionMouseClicked

    private void lblFunctionMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFunctionMouseExited
    {//GEN-HEADEREND:event_lblFunctionMouseExited
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblFunction, false);
    }//GEN-LAST:event_lblFunctionMouseExited

    private void lblFormatsMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFormatsMouseClicked
    {//GEN-HEADEREND:event_lblFormatsMouseClicked
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblFormats, true);
        lblFormats.setBackground(new Color(0, 0, 0));
        //MUST FID MORE EFFICIENT WAY - MAYBE SET STATE OF VISIBLE IN VARIABLE
        rename.setVisible(false);
        functions.setVisible(false);
        variables.setVisible(false);
        help.setVisible(false);
        formats.setVisible(true);       
    }//GEN-LAST:event_lblFormatsMouseClicked

    private void lblFormatsMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFormatsMouseEntered
    {//GEN-HEADEREND:event_lblFormatsMouseEntered
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblFormats, true);
    }//GEN-LAST:event_lblFormatsMouseEntered

    private void lblFormatsMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblFormatsMouseExited
    {//GEN-HEADEREND:event_lblFormatsMouseExited
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblFormats, false);
    }//GEN-LAST:event_lblFormatsMouseExited

    private void lblVariablesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblVariablesMouseClicked
    {//GEN-HEADEREND:event_lblVariablesMouseClicked
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblVariables, true);
        lblVariables.setBackground(new Color(0, 0, 0));
        rename.setVisible(false);
        functions.setVisible(false);
        variables.setVisible(true);
        help.setVisible(false);
        formats.setVisible(false);
    }//GEN-LAST:event_lblVariablesMouseClicked

    private void lblVariablesMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblVariablesMouseEntered
    {//GEN-HEADEREND:event_lblVariablesMouseEntered
        // TODO add your handling code here:  
        resetSideMenu(sideMenu, lblVariables, true);
    }//GEN-LAST:event_lblVariablesMouseEntered

    private void lblVariablesMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblVariablesMouseExited
    {//GEN-HEADEREND:event_lblVariablesMouseExited
        // TODO add your handling code here:   
        resetSideMenu(sideMenu, lblVariables, false);
    }//GEN-LAST:event_lblVariablesMouseExited

    private void lblHelpMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblHelpMouseEntered
    {//GEN-HEADEREND:event_lblHelpMouseEntered
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblHelp, true);
    }//GEN-LAST:event_lblHelpMouseEntered

    private void lblHelpMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblHelpMouseExited
    {//GEN-HEADEREND:event_lblHelpMouseExited
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblHelp, false);
    }//GEN-LAST:event_lblHelpMouseExited

    private void lblHelpMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblHelpMouseClicked
    {//GEN-HEADEREND:event_lblHelpMouseClicked
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblHelp, true);
        lblHelp.setBackground(new Color(0, 0, 0));
        rename.setVisible(false);
        functions.setVisible(false);
        variables.setVisible(false);
        help.setVisible(true);
        formats.setVisible(false);
    }//GEN-LAST:event_lblHelpMouseClicked

    private void lblRenameMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblRenameMouseEntered
    {//GEN-HEADEREND:event_lblRenameMouseEntered
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblRename, true);
    }//GEN-LAST:event_lblRenameMouseEntered

    private void lblRenameMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblRenameMouseClicked
    {//GEN-HEADEREND:event_lblRenameMouseClicked
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblRename, true);
        lblRename.setBackground(new Color(0, 0, 0));
        rename.setVisible(true);
        functions.setVisible(false);
        variables.setVisible(false);
        help.setVisible(false);
        formats.setVisible(false);
    }//GEN-LAST:event_lblRenameMouseClicked

    private void lblRenameMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblRenameMouseExited
    {//GEN-HEADEREND:event_lblRenameMouseExited
        // TODO add your handling code here:
        resetSideMenu(sideMenu, lblRename, false);
    }//GEN-LAST:event_lblRenameMouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblMinimizeMouseClicked
    {//GEN-HEADEREND:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState( JFrame.ICONIFIED );
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblExitMouseEntered
    {//GEN-HEADEREND:event_lblExitMouseEntered
        // TODO add your handling code here:
        lblExit.setBackground(new Color(232, 17, 35));        
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblExitMouseExited
    {//GEN-HEADEREND:event_lblExitMouseExited
        // TODO add your handling code here:
        lblExit.setBackground(new Color(204,204,204)); 
    }//GEN-LAST:event_lblExitMouseExited

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblMinimizeMouseEntered
    {//GEN-HEADEREND:event_lblMinimizeMouseEntered
        // TODO add your handling code here:
        lblMinimize.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblMinimizeMouseExited
    {//GEN-HEADEREND:event_lblMinimizeMouseExited
        // TODO add your handling code here:
        lblMinimize.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lblMinimizeMouseExited

    public void resetSideMenu(JPanel panel, JLabel item, boolean entered)
    {
        if (entered)
        {
            item.setBackground(new Color(0, 0, 0));
            for (Component c : panel.getComponents())
            {

                if (!c.getName().equals(item.getName()) && !c.getName().equals("menu"))
                {
                    c.setBackground(new Color(39, 43, 54));
                }
            }

        }
        else
        {
            item.setBackground(new Color(39, 43, 54));
            for (Component c : panel.getComponents())
            {
                if (!c.getName().equals(item.getName()) && !c.getName().equals("menu"))
                {
                    c.setBackground(new Color(39, 42, 54));
                }
            }
        }        
        
    }    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FrameDrag;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFormats;
    private javax.swing.JLabel lblFunction;
    private javax.swing.JLabel lblHamburgerMenu;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblRename;
    private javax.swing.JLabel lblVariables;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JPanel titleBar;
    // End of variables declaration//GEN-END:variables
}
